
# Header for the message
std_msgs/Header header

# Front End Voltage of Main Contactor (in volts)
int64 front_end_voltage

# Back End Voltage of Main Contactor (in volts)
int64 back_end_voltage

# AC Current Effective Value (in amperes)
int64 ac_current_effective_value

# Temperature of the Motor Controller (in degrees Celsius)
int64 motor_controller_temperature

# Temperature of the Motor (in degrees Celsius)
int64 motor_temperature
